---

iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

  compilation_cloud_properties: {}

  watch_time: 10000-120000

  resource_pool_cloud_properties:
  - name: splunk_z1
    cloud_properties: {}
  - name: errands_z1
    cloud_properties: {}

  subnet_configs:
  - name: splunk_z1
    subnets:
    - cloud_properties:
        name: random
      range: 10.244.15.0/24
      reserved:
      - 10.244.15.1
      static:
      - 10.244.15.2 - 10.244.15.20
